### ISSUE TITLE
Some things that could be better to be honest.

### ISSUE THREAD

**Issue by benzon** [qalle-fivem/esx-qalle-jail#4]
Check that you are a cop when opening the menu right now everyone can open that up.

Check if you are in jail right now you can work out the front door, if you want to, and when you are in prisson you should not be able to go to security to be honest.

And if you are a visitor you should not be able to go in to the jail area, only in to the visitors room.

**Comment by benzon** [comment]
Ye thats the issue you should add

`RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
  PlayerData.job = job
end)`

just after esx:playerLoaded in client then it looks to update the right way :)

**Comment by benzon** [comment]
Minor question tho, with the script on PED's are spawning inside the security part of the jail, with out the script there is none, did you add something or ?

**Comment by qalle-fivem** [comment]
@benzon I did not add any extra thing for the peds, really dont know. setjob added. Ill check on that if he is in jail not to teleport.
